[build]
  base = "."
  functions = "functions"
  command = "npm run build"
  publish = "public"


[[redirects]]
  from = "/processar-formulario"
  to = "/.netlify/functions/processar-formulario"
  status = 200
